### ISSUE TITLE
feedback component not matching designs

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#60]
![feedback-component](https://cloud.githubusercontent.com/assets/5955676/24893711/14827bfc-1ea3-11e7-8b71-52f14a23cefd.png)

**Comment by joshpitzalis** [comment]
Fixed in https://github.com/qjflores/exchangemvpreact/pull/62 . Just html/css in a form element The event hasn't been handled in anyway. Sumukh wasn't sure if we should give people stars to rate or juste give them a trust/block option that we then calculate a score from. I built all three so that we can pick.
