### ISSUE TITLE
ad list is different from designs

### ISSUE THREAD

**Issue by sumukhshetty** [qjflores/exchangemvpreact#81]
<img width="1082" alt="screen shot 2017-04-17 at 4 05 42 pm" src="https://cloud.githubusercontent.com/assets/22879373/25086759/bd731e40-2387-11e7-95f3-c7d9888eef63.png">

**Comment by joshpitzalis** [comment]
fixed in https://github.com/qjflores/exchangemvpreact/pull/115

active buy ads now look like...
![buy](https://cloud.githubusercontent.com/assets/10258114/25221344/6be34634-25d2-11e7-9669-5606f976404c.png)

and sell ads...
![sell](https://cloud.githubusercontent.com/assets/10258114/25221356/7904278e-25d2-11e7-9616-eec4e081c3eb.png)

populated the data as best I could with props but I didn't figure some out so I left little 'fix' me placeholders.

**Comment by sumukhshetty** [comment]
that looks good josh.
 @adklempner  can you work with this ?
